// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_vEAeFN4lNb1RtuDZ7Hjj-UbywBJZbNM',
    appId: '1:1089602527794:web:029efd405b14128df2922b',
    messagingSenderId: '1089602527794',
    projectId: 'ajent-major-project',
    authDomain: 'ajent-major-project.firebaseapp.com',
    storageBucket: 'ajent-major-project.appspot.com',
    measurementId: 'G-28K8EJ240N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTaRVMSnoJS9UnRumU38gDQRSbUKHQKE',
    appId: '1:1089602527794:android:2100b1d3fc5c2fedf2922b',
    messagingSenderId: '1089602527794',
    projectId: 'ajent-major-project',
    storageBucket: 'ajent-major-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAasGEpts9O-lLASZj5_IvMUFMSvSNltvY',
    appId: '1:1089602527794:ios:0b3ab6fe1c8541c4f2922b',
    messagingSenderId: '1089602527794',
    projectId: 'ajent-major-project',
    storageBucket: 'ajent-major-project.appspot.com',
    androidClientId: '1089602527794-b3vdbmdr2mv1lt7pt8vvelegudri8qv3.apps.googleusercontent.com',
    iosClientId: '1089602527794-fqj1gk9i948vsbr97o24j8m96l0n6cjd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ajent',
  );
}
